export { default as CategoryPc } from './category/CategoryPc'
export { default as CategoryTablet } from './category/CategoryTablet'
export { default as CreatedProducts } from './products/createdProducts/CreatedProducts'
export { default as FavoriteProducts } from './products/favoriteProducts/FavoriteProducts'
export { default as ReviewedProducts } from './products/reviewedProducts/ReviewedProducts'
export { default as ProductCardSection } from './section/ProductCardSection'
export { default as EmptyProduct } from './products/empty-product/EmptyProduct'
