export { default as CategoryPc } from './category/CategoryPc'
export { default as CategoryTablet } from './category/CategoryTablet'
export { default as CreatedProducts } from './products/CreatedProducts'
export { default as FavoriteProducts } from './products/FavoriteProducts'
export { default as ReviewedProducts } from './products/ReviewedProducts'
export { default as ProductCardSection } from './section/ProductCardSection'
